# Generated by Django 3.1.2 on 2020-11-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201113_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsetting',
            name='allow_discussion',
            field=models.BooleanField(verbose_name='allow discussion'),
        ),
    ]
