# Generated by Django 3.1.3 on 2020-11-22 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20201113_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', related_query_name='comment_like', to='blog.comment', verbose_name='Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('author', 'comment')},
        ),
    ]
