# Generated by Django 3.1.3 on 2020-11-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201124_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsetting',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', related_query_name='setting', to='blog.post', verbose_name='post'),
        ),
    ]
