# Generated by Django 3.1.3 on 2020-11-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201127_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsetting',
            name='allow_discussion',
            field=models.BooleanField(default=False, verbose_name='allow discussion'),
        ),
        migrations.AlterField(
            model_name='postsetting',
            name='author',
            field=models.BooleanField(default=False, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='postsetting',
            name='comment',
            field=models.BooleanField(default=True, verbose_name='comment'),
        ),
    ]
